"""add_source_to_document

Revision ID: 4d7b51282248
Revises: ddbab9727dfc
Create Date: 2026-04-22 04:50:58.655153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7b51282248'
down_revision: Union[str, None] = 'ddbab9727dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('source', sa.String(length=50), server_default='text', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'source')
    # ### end Alembic commands ###
