"""add_extraction_metadata

Revision ID: 9c5192f3132e
Revises: 4d7b51282248
Create Date: 2026-04-27 07:52:41.935854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c5192f3132e'
down_revision: Union[str, None] = '4d7b51282248'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('chunk_type', sa.String(length=20), server_default='text', nullable=False))
    op.add_column('chunk', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('chunk', sa.Column('section_heading', sa.String(length=500), nullable=True))
    op.add_column('chunk', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('chunk', sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_chunk_page_number'), 'chunk', ['page_number'], unique=False)
    op.add_column('document', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('document', sa.Column('scanned_pages', postgresql.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    op.add_column('document', sa.Column('extraction_status', sa.String(length=20), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'extraction_status')
    op.drop_column('document', 'scanned_pages')
    op.drop_column('document', 'page_count')
    op.drop_index(op.f('ix_chunk_page_number'), table_name='chunk')
    op.drop_column('chunk', 'bbox')
    op.drop_column('chunk', 'confidence')
    op.drop_column('chunk', 'section_heading')
    op.drop_column('chunk', 'page_number')
    op.drop_column('chunk', 'chunk_type')
    # ### end Alembic commands ###
